// Events
const HISTORY_CHANGED = "HISTORY_CHANGED";
const SEARCH_CHANGED = "SEARCH_CHANGED";
const DELETE_ITEM_CLICKED = "DELETE_ITEM_CLICKED";
const DELETE_HISTORY_CLIKED = "DELETE_HISTORY_CLIKED";
const QUERY_CHANGED = "QUERY_CHANGED";
const SEARCH_SUBMITTED = "SEARCH_SUBMITTED";

// Other
const HISTORY = "HISTORY";
